# Copyright 2026 Jordy Slagter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - WEBUI_AUTH=False
    volumes:
      - open-webui:/app/backend/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.localhost`)"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    # nvidia only:
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities:
#                - gpu
volumes:
  open-webui:
  ollama:
networks:
  proxy:
    external: true
