services:
  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - WEBUI_AUTH=False
    volumes:
      - open-webui:/app/backend/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    # nvidia only:
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities:
#                - gpu
volumes:
  open-webui:
  ollama:
networks:
  proxy:
    external: true
